name: Publish (npm)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno test
      - run: deno task pack
      - run: npm publish ./shresht7-http-status-codes-*.tgz --dry-run

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
      - run: deno task pack
      - run: npm publish ./shresht7-http-status-codes-*.tgz --provenance
